### ISSUE TITLE
Serious problem for loading code on Windows.. tested many drivers, cuda toolkit and pytorch versions!

### ISSUE THREAD

**Issue by profile838** [jqtangust/EPCE-HDR#4]
`(hdr) C:\Users\mikazmaj\EPCE-HDR\codes>python test.py -opt options/test/test.yml
export CUDA_VISIBLE_DEVICES=1
24-01-13 19:49:11.703 - INFO:   name: Ours-Original
  model: condition
  distortion: sr
  scale: 1
  gpu_ids: [1]
  datasets:[
    test_1:[
      name: 000_Valid_SingleFrame_FirstStage
      mode: LQ_condition
      dataroot_LQ: C:\Users\mikazmaj\EPCE-HDR\test
      condition: image
      phase: test
      scale: 1
      data_type: img
    ]
  ]
  network_G:[
    which_model_G: EPCE
    in_nc: 3
    out_nc: 3
    nf: 64
    act_type: relu
    scale: 1
  ]
  path:[
    root: C:\Users\mikazmaj\EPCE-HDR\./
    pretrain_model_G: /home/jiaqitang/HDR_all/Final_Ours/experiments/Final_Ours-Original/models/20000_G.pth
    results_root: C:\Users\mikazmaj\EPCE-HDR\./results\Ours-Original
    log: C:\Users\mikazmaj\EPCE-HDR\./results\Ours-Original
  ]
  is_train: False

img C:\Users\mikazmaj\EPCE-HDR\test
24-01-13 19:49:12.277 - INFO: Dataset [LQ_Dataset - 000_Valid_SingleFrame_FirstStage] is created.
24-01-13 19:49:12.277 - INFO: Number of test images in [000_Valid_SingleFrame_FirstStage]: 72
Traceback (most recent call last):
  File "C:\Users\mikazmaj\EPCE-HDR\codes\test.py", line 38, in <module>
    model = create_model(opt,0)
  File "C:\Users\mikazmaj\EPCE-HDR\codes\models\__init__.py", line 14, in create_model
    m = M(opt,tb_logger)
  File "C:\Users\mikazmaj\EPCE-HDR\codes\models\Generation_condition.py", line 29, in __init__
    self.netG = networks.define_G(opt,tb_logger).to(self.device)
  File "C:\Users\mikazmaj\anaconda3\envs\hdr\lib\site-packages\torch\nn\modules\module.py", line 1160, in to
    return self._apply(convert)
  File "C:\Users\mikazmaj\anaconda3\envs\hdr\lib\site-packages\torch\nn\modules\module.py", line 810, in _apply
    module._apply(fn)
  File "C:\Users\mikazmaj\anaconda3\envs\hdr\lib\site-packages\torch\nn\modules\module.py", line 810, in _apply
    module._apply(fn)
  File "C:\Users\mikazmaj\anaconda3\envs\hdr\lib\site-packages\torch\nn\modules\module.py", line 833, in _apply
    param_applied = fn(param)
  File "C:\Users\mikazmaj\anaconda3\envs\hdr\lib\site-packages\torch\nn\modules\module.py", line 1158, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "C:\Users\mikazmaj\anaconda3\envs\hdr\lib\site-packages\torch\cuda\__init__.py", line 298, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available`

conda list:
https://pastebin.com/jqB335sk

please fix! And provide a link for pth model!
Thanks

**Comment by jqtangust** [comment]
Can you try this: https://stackoverflow.com/questions/62359175/pytorch-says-that-cuda-is-not-available-on-ubuntu

It seems a cuda or gcc problem.

**Comment by zelenooki87** [comment]
No. you do not provided pth model!  That is it!

**Comment by jqtangust** [comment]
pls try again for this new version.
